backend:
  name: git-gateway
  branch: zimmerfrei-with-netlifycms

media_folder: static/img
public_folder: static/img

collections:
  - label: "Seiten"
    name: "pages"
    files:
      - label: "Die Zimmer"
        name: "zimmer"
        file: "src/pages/zimmer.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}